INSERT INTO tb_user (name, email, password) VALUES ('Bob Brown', 'bob@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, email, password) VALUES ('Ana Green', 'ana@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');

INSERT INTO tb_role (authority) VALUES ('ROLE_VISITOR');
INSERT INTO tb_role (authority) VALUES ('ROLE_MEMBER');

INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);

INSERT INTO tb_genre (name) VALUES ('Aventura');
INSERT INTO tb_genre (name) VALUES ('Ação');
INSERT INTO tb_genre (name) VALUES ('Romance');
INSERT INTO tb_genre (name) VALUES ('Fantasia');
INSERT INTO tb_genre (name) VALUES ('Drama');
INSERT INTO tb_genre (name) VALUES ('Luta');
INSERT INTO tb_genre (name) VALUES ('Terror');

INSERT INTO tb_movie (title, subtitle, year, img_url, synopsis, genre_id) VALUES ('Senhor dos Aneis', 'A Sociedade do Anel', 2001, 'https://upload.wikimedia.org/wikipedia/pt/3/38/Lord_of_the_Rings_Fellowship_of_the_Ring.jpg', 'Numa terra fantástica e única, chamada Terra-Média, um hobbit (seres de estatura entre 80 cm e 1,20 m, com pés peludos e bochechas um pouco avermelhadas) recebe de presente de seu tio o Um Anel, um anel mágico e maligno que precisa ser destruído antes que caia nas mãos do mal. Para isso o hobbit Frodo (Elijah Woods) terá um caminho árduo pela frente, onde encontrará perigo, medo e personagens bizarros. Ao seu lado para o cumprimento desta jornada aos poucos ele poderá contar com outros hobbits, um elfo, um anão, dois humanos e um mago, totalizando 9 pessoas que formarão a Sociedade do Anel.', 1);
INSERT INTO tb_movie (title, subtitle, year, img_url, synopsis, genre_id) VALUES ('Robocop', 'O policial do futuro', 1987, 'https://www.pontofrio-imagens.com.br/dvdsebluray/FilmeseSeriados/BluRayPolicial/435965/4581505/DVD-Robocop-O-Policial-Do-Futuro-435965.jpg', 'Alguns anos no futuro, Detroit no estado de Michigan é quase uma distopia à beira do colapso devido à ruína financeira e à criminalidade descontrolada. Para escapar ao colapso, o presidente da câmara da cidade assinou um acordo com a megacorporação Omni Consumer Products (OCP), dando-lhes o controle das forças policiais arruinadas, em troca de permitir à OCP demolir as seções degradadas de Detroit e construir uma cidade utópica, a "Delta City", uma cidade-estado independente gerida pela corporação.', 2);
INSERT INTO tb_movie (title, subtitle, year, img_url, synopsis, genre_id) VALUES ('Blade', 'Trinity', 2004, 'https://upload.wikimedia.org/wikipedia/pt/thumb/9/91/Blade_Trinity.jpg/240px-Blade_Trinity.jpg', 'Os líderes dos vampiros estão ressuscitando o vampiro Drácula, a criatura terrível que foi a origem de sua raça. Agora conhecido como Drake (Dominic Purcell) tem poderes exclusivos que lhe permitem caminhar na luz do sol. O meio-vampiro Blade (Wesley Snipes) passa por uma situação complicada quando os líderes vampiros lançam uma campanha difamatória contra ele, chamando-o de um monstro assassino e instigar o FBI a ir atrás dele. ', 2);
INSERT INTO tb_movie (title, subtitle, year, img_url, synopsis, genre_id) VALUES ('Rambo', 'First Blood', 1982, 'https://upload.wikimedia.org/wikipedia/pt/thumb/5/54/Rambo_First_Blood_1982.jpg/200px-Rambo_First_Blood_1982.jpg', 'Rambo: First Blood, ou simplesmente Rambo (como ficou conhecido no Brasil e em Portugal), é um filme norte-americano de 1982 dirigido por Ted Kotcheff, produzido por Mario Kassar e Andrew G. Vajna, com roteiro de David Morrell, Michael Kozoll, William Sackheim e Sylvester Stallone. A história é baseada na obra de mesmo título de David Morrell, publicada em 1972. O título original First Blood refere-se à frase do personagem Rambo They drew first blood, not me!, dita durante o filme.', 2);
INSERT INTO tb_movie (title, subtitle, year, img_url, synopsis, genre_id) VALUES ('Indiana Jones', 'E Os Caçadores da Arca Perdida', 1981, 'https://upload.wikimedia.org/wikipedia/pt/thumb/4/4b/Raiders.jpg/250px-Raiders.jpg', 'Indiana Jones e Os Caçadores da Arca Perdida /Portugal: Os Salteadores da Arca Perdida) é um filme de aventura americano, dirigido por Steven Spielberg, que estreou em 1981. Foi produzido por Frank Marshall e Howard Kazanjian, com produção executiva de George Lucas, roteiro de Lawrence Kasdan, baseado em um tratamento de George Lucas e Philip Kaufman. É o primeiro filme da saga Indiana Jones e o segundo da cronologia da série. Ele coloca Indiana Jones contra um grupo de nazistas que estão procurando a Arca da Aliança, que Adolf Hitler acredita que possa tornar o seu exército invencível. O filme é estrelado por Harrison Ford, Karen Allen, Paul Freeman, John Rhys-Davies, Ronald Lacey e Denholm Elliott.', 2);
INSERT INTO tb_movie (title, subtitle, year, img_url, synopsis, genre_id) VALUES ('O Poderoso Chefão', 'Trilogia', 1981, 'https://filmeshdtorrent.net/imagem/trilogia-o-poderoso-chefao-torrent.jpg', 'O Poderoso Chefão Dublado, Indiscutivelmente é uma das obras-primas do cinema americano. Marcou a carreira de Marlon Brando no papel principal do filme. Baseado no best-seller de Mario Puzo, O Poderoso Chefão é um verdadeiro fenômeno cultural que ultrapassou US$ 100 milhões de arrecadação, contando a história da família Corleone', 5);
INSERT INTO tb_movie (title, subtitle, year, img_url, synopsis, genre_id) VALUES ('Rocky', 'Toda a sua vida foi um tiro de um milhão para um', 1976, 'https://upload.wikimedia.org/wikipedia/pt/1/18/Rocky_poster.jpg', 'Rocky é um desconhecido boxeador da Filadélfia que complementa sua renda como coletor de um agiota. Nesta cidade ocorrerá a disputa pelo campeonato mundial de pesos pesados, que está marcada para o dia de Ano Novo de 1976, o ano do bicentenário da Declaração da Independência dos Estados Unidos. Porém, o desafiante do campeão Apollo Creed se machuca, e o promotor Jergens encontra dificuldades de encontrar outro oponente. Creed apresenta a ideia incomum de lutar contra um lutador local, de origem italiana: sua escolha recai em Rocky, apelidado Rocky, The Italian Stallion (O Garanhão Italiano), imaginando ser um grande apelo para a mídia.', 5);
INSERT INTO tb_movie (title, subtitle, year, img_url, synopsis, genre_id) VALUES ('Brinquedo Assassino', 'Vem bricar comigo', 1988, 'http://br.web.img2.acsta.net/pictures/14/10/10/18/18/494547.jpg', 'Após a babá do garotinho de seis anos Andy Barclay ser violentamente arremessada pela janela, ninguém acredita nele quando diz que Chucky , o boneco que ganhou de aniversário, foi o culpado! Até que as coisas começam a dar errado… mortalmente errado. E quando uma série de terríveis assassinatos leva um detetive de volta ao mesmo brinquedo, ele descobre que o verdadeiro terror tinha apenas começado - o boneco perturbado planeja transferir seu espírito mau para um ser vivo - o pequeno Andy.', 7);
INSERT INTO tb_movie (title, subtitle, year, img_url, synopsis, genre_id) VALUES ('De Volta para o Futuro', 'A Trilogia', 1985, 'https://blogdoheu.files.wordpress.com/2010/12/devoltaparaofuturocapat.jpg', 'De Volta para o Futuro - pt: Regresso ao Futuro) é um filme norte-americano de 1985. Foi dirigido por Robert Zemeckis e escrito por Zemeckis e Bob Gale. Estrelado por Michael J. Fox, Christopher Lloyd, Lea Thompson, Crispin Glover e Thomas F. Wilson. O filme conta a história de Marty McFly (Michael J. Fox), um adolescente que inevitavelmente volta no tempo até 1955. Ele conhece seus futuros pais no colégio e acidentalmente faz sua futura mãe ficar romanticamente interessada por ele. Marty deve consertar o dano na história fazendo com que seus pais se apaixonem e, com a ajuda do Dr. Emmett Brown (Christopher Lloyd), encontrar um modo de voltar para 1985.', 1);
INSERT INTO tb_movie (title, subtitle, year, img_url, synopsis, genre_id) VALUES ('Os Goonies', 'Quero Chocolate', 1985, 'https://upload.wikimedia.org/wikipedia/pt/thumb/9/92/Goonies.jpg/240px-Goonies.jpg', 'Após encontrar um mapa do tesouro no sótão de sua casa, Mickey, Brand, Bocão (Mouth), Dado (Data) e Gordo (Chunk) partem em busca do tesouro de Willy Caolho. Juntam-se a eles nessa aventura Andy e Stef mas, além das armadilhas deixadas por Willy Caolho por entre as cavernas e trilhas subterrâneas, os garotos terão de enfrentar também uma família de bandidos italianos, Os Fratelli. Para salvá-los resta somente o valente e destemido Sloth.', 1);

INSERT INTO tb_review (text, movie_id) VALUES ('Melhor filme ja feito, 100 estrels de 10 ;D.', 1);
INSERT INTO tb_review (text, movie_id) VALUES ('Show de Filme', 2);
INSERT INTO tb_review (text, movie_id) VALUES ('Filme supimpa', 3);
INSERT INTO tb_review (text, movie_id) VALUES ('Filme de morrer', 4);
INSERT INTO tb_review (text, movie_id) VALUES ('Minha mãe adora esse filme', 5);
INSERT INTO tb_review (text, movie_id) VALUES ('Esse filme so tem estrelas',6);
INSERT INTO tb_review (text, movie_id) VALUES ('Maravilha de filme', 7);
INSERT INTO tb_review (text, movie_id) VALUES ('Olha depois que vi esse filme minha vida mudou', 8);
INSERT INTO tb_review (text, movie_id) VALUES ('Como eu queria ter uma maquina do tempo', 9);
INSERT INTO tb_review (text, movie_id) VALUES ('Marcou minha infância.', 10);